### ISSUE TITLE
Error in `$<-.data.frame`

### ISSUE THREAD

**Issue by mgsrod** [Simon-Leonard/APERO#10]
Hi,
I receive the following error when I attempt to run APERO:

> Start detection with window = 1Error in `$<-.data.frame`(`*tmp*`, "ws", value = 0) : 
>   replacement has 1 row, data has 0
> In addition: Warning message:
> In max(which(let < le[i])) :
>   no non-missing arguments to max; returning -Inf

My input is as follows:b.  APERO_start_detection(work_dir = ("/apero"), bam_name = "sortedbam.bam", ptt_file = NULL, wmax = 10, min_dist = 10, enrichment = 0.1, min_read_number = 0, genome_size = 2000000)

APERO is working with the sample data using the same options. 

My BAM file is sorted and seems complete:
@HD     VN:1.0  SO:coordinate
@SQ     SN:KQ033870.1   LN:107658
@SQ     SN:KQ033871.1   LN:2001565
@SQ     SN:KQ033872.1   LN:3680
@SQ     SN:KQ033873.1   LN:1903
@SQ     SN:KQ033874.1   LN:1484
@SQ     SN:KQ033875.1   LN:1478
@SQ     SN:KQ033876.1   LN:610
@PG     ID:bowtie2      PN:bowtie2      VN:2.2.5 

Any ideas on how to fix this issue?

All the best,

Rod

**Comment by Simon-Leonard** [comment]
Hi Rod,

Is your data single end ?

Best,
Simon

**Comment by mgsrod** [comment]
Hi Simon,
Thanks for getting back to me so soon.
Yes, its single end data.

**Comment by mgsrod** [comment]
Hi Simon,

Yes, it’s single end data


Rod Eyles, PhD
Post Doctoral Researcher,
Microbial Genomics & Symbiosis Lab
***@***.*** 

Instituto Gulbenkian de Ciência
Rua da Quinta Grande 6 2780-156 Oeiras, Portugal
Website <https://gulbenkian.pt/ciencia/>  |  Facebook <https://www.facebook.com/InstitutoGulbenkianCiencia>  |  Instagram  <https://www.instagram.com/igciencia/?hl=en> |  Twitter <https://twitter.com/igciencia>  |  LinkedIn <https://www.linkedin.com/company/instituto-gulbenkian-de-ciencia/>￼

**Comment by Simon-Leonard** [comment]
Initially APERO was not dedicated to work on single end data but I had some requests so I created a separated branch in github.
Can you try the procedure mentionned in https://github.com/Simon-Leonard/APERO/issues/3#issuecomment-605458633 ?
You just have to install a particular branch and add a parameter to the functions.

Simon
