### ISSUE TITLE
single-end data

### ISSUE THREAD

**Issue by Jomagrax** [Simon-Leonard/APERO#3]
Hi, I am seriusly considering using this software but my data is single-end, could I still use It?

**Comment by Simon-Leonard** [comment]
Hi, 
I have updated the programm in a new branch to support single end data analysis.
You can install this version with : 
install_github("Simon-Leonard/APERO", ref = "single_end_compatibility")

To check that you have the correct version, you should have a new argument (paired_end_data) in both APERO_start_detection and APERO_end_detection functions.
The default value of paired_end_data is TRUE so set it to FALSE and it should works =)

Simon

**Comment by Jomagrax** [comment]
Hi simon,

Thank you very much for your help, I'll let you know if It work, you saved
my life!!

Jose.
