### ISSUE TITLE
APERO_end_detection output

### ISSUE THREAD

**Issue by KKotryna** [Simon-Leonard/APERO#5]
Hi, 
I wanted to ask about APERO_end_detection output. As I understand it should be a table containing start and end positions for each sRNA. I ran APERO with example BAM file and example script. The colnames of my results variables are: 

```
colnames(res2)
[1] "ID_Transcrit"           "Position"               "Positional.Uncertainty"
 [4] "lg"                     "str"                    "freq"                  
 [7] "iteration_nb"           "last_Ftsse"             "Class"                 
[10] "Comment"               
```

Could you please provide more details/explanations about each column and its meaning?

**Comment by Simon-Leonard** [comment]
Hi,

Here is a description of each column :
ID_Transcrit : Detected transcript ID
Position : Start position of the detected transcript
Positional.Uncertainty : Uncerntainty of the detected position (in nt)
lg : Length of the detected RNA
str : Strand of the detected RNA
freq : Number of reads at the start positions
iteration_nb : Number of iterations used to detect the RNA end (See the end detection method in APERO paper)
last_Ftsse : Laste Ftsse value (see the APERO paper for the definition of Ftsse)
Class : Annotation of the detected RNA according to supplementary figure 2 in APERO paper 
Comment : Detailed annotation

I will add this to the read me !

Bests,
Simon
