### ISSUE TITLE
Run with muiltiple BAM files

### ISSUE THREAD

**Issue by osvaldoreisss** [Simon-Leonard/APERO#6]
Hi, first I would like to thank you for you program.
I'm planning to use it in my analysis and a got it working for one sample, but I wanted to know how I should proceed when I have replicates from multiples conditions. Should I run for each BAM and after try to get a consensus?

Thanks,

**Comment by Simon-Leonard** [comment]
Hi,
Yes, you're right
If you have multiple bam files from multiple conditions and you want to compare each condition to each other,  you have to run APERO on each BAM separately and compare detected transcripts.

If you have technical replicates (multiple bam from same condition), it could be easier to merge the corresponding bam file has you will have only one set of parameters.

Bests,
Simon
