### ISSUE TITLE
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated

### ISSUE THREAD

**Issue by wanjinhu** [Simon-Leonard/APERO#7]
Hi @Simon-Leonard 

when i use the example data to test APERO，command line just like below:

'ptt=read.csv("NC_016810.ptt", sep="\t", skip=2, header=T, stringsAsFactors = F)'

'res=APERO_start_detection(work_dir = "home/APERO/", bam_name = "SRR2149882_position_1_to_10kb.bam", ptt_file =ptt, wmax = 10, min_dist = 10, enrichment = 0.1, min_read_number = 0, genome_size = 4878012)'

'res2=APERO_end_detection(work_dir = "home/APERO/", start_table = res, mTEX_bam = "SRR2149882_position_1_to_10kb.bam", readthrough_proportion = 0.01, Fmin=NA, thread_number = 8, genome_size = 4878012, ptt_file=ptt)'

when i run step 2 and 3, there are error warning, just like:
'[W::bam_hdr_read] EOF marker is absent. The input is probably truncated'

'[E::bgzf_read] Read block operation failed with error -1 after 4 of 19 bytes'

can you help me with this problem?

also, what does the result of APERO look like? have any example?

**Comment by wanjinhu** [comment]
i think i have solved this problem.

**Comment by Simon-Leonard** [comment]
Hi @wanjinhu 
Thank you for using APERO.
APERO result is described in the github readme file (see "Usage").

Can you tell me how you fixed the issue ?

Bests,
