### ISSUE TITLE
APERO end detection output

### ISSUE THREAD

**Issue by anfarr** [Simon-Leonard/APERO#9]
Hi,

Here is a description of each column :
ID_Transcrit : Detected transcript ID
Position : Start position of the detected transcript
Positional.Uncertainty : Uncerntainty of the detected position (in nt)
lg : Length of the detected RNA
str : Strand of the detected RNA
freq : Number of reads at the start positions
iteration_nb : Number of iterations used to detect the RNA end (See the end detection method in APERO paper)
last_Ftsse : Laste Ftsse value (see the APERO paper for the definition of Ftsse)
Class : Annotation of the detected RNA according to supplementary figure 2 in APERO paper 
Comment : Detailed annotation

I will add this to the read me !

Bests,
Simon

_Originally posted by @Simon-Leonard in https://github.com/Simon-Leonard/APERO/issues/5#issuecomment-632677901_

Hey Simon,
i have two questions.
Shouldn't last_Ftsse be defined as "last Fstart,e" to make the connection to the paper?
And is the coordinate of the position, 0 based like the bam file or 1-based?
Best regards,
Anton

**Comment by Simon-Leonard** [comment]
Hi,

That is correct, last_Ftsse corresponds to last Fstart,e.
The coordinates are 1-based.

Simon
